name: Build Images
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --volume /dev:/dev --privileged
    defaults:
      run:
        shell: bash
    steps:
    - name: update packages
      run: pacman --noconfirm -Syu
    - name: install packages
      run: pacman --noconfirm --needed -S arch-install-scripts syslinux parted gptfdisk dosfstools git
    - name: checkout
      uses: actions/checkout@v3
    - name: build hybred image
      run: ./build.sh
    - name: compress hybred image
      run: |
        ./compress.sh
        mv ./arch.img.gz ./arch-hybred.img.gz
    - name: build bios image
      run: ./build-bios.sh
    - name: compress bios image
      run: |
        ./compress.sh
        mv ./arch.img.gz ./arch-bios.img.gz
    - name: Create and Upload Release
      if: contains(github.ref, '/tags/')
      uses: softprops/action-gh-release@v1
      with:
        prerelease: ${{ endsWith(github.ref, '-dev') }}
        files: '*.gz'
